/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab7p2_carlosmoncada;

import java.awt.Color;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author calol
 */
public class Pantalla extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        edad_spinner = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        txt_profesion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_sueldodisponible = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txt_marca = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_modelo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_año = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_precioventa = new javax.swing.JTextField();
        jToggleButton2 = new javax.swing.JToggleButton();
        txt_color = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txt_nombrevendedor = new javax.swing.JTextField();
        jToggleButton3 = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        cb_vendedor = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cb_comprador = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        costotransaccion = new javax.swing.JTextField();
        cb_vehiculo = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        arbolitosexy = new javax.swing.JTree();
        jToggleButton6 = new javax.swing.JToggleButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        arbolclase = new javax.swing.JTree();
        jToggleButton7 = new javax.swing.JToggleButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        limp = new javax.swing.JTree();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        area_salida = new javax.swing.JTextArea();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("edad");

        jLabel3.setText("Profesion");

        jLabel4.setText("Sueldo disponible");

        jToggleButton1.setText("Crear Cliente");
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_sueldodisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_profesion)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(edad_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jToggleButton1)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(edad_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_profesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_sueldodisponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addGap(41, 41, 41))
        );

        menu.addTab("Crear Cliente", jPanel1);

        jLabel5.setText("Marca");

        jLabel6.setText("Color");

        jLabel7.setText("Modelo");

        jLabel8.setText("Año");

        jLabel9.setText("Precio venta");

        jToggleButton2.setText("Crear vehiculo");
        jToggleButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_marca, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                    .addComponent(txt_color)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_modelo, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_precioventa, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                            .addComponent(txt_año))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jToggleButton2)))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_precioventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButton2)
                .addContainerGap())
        );

        menu.addTab("Crear vehiculo", jPanel2);

        jLabel10.setText("Nombre");

        jToggleButton3.setText("Crear vendedor");
        jToggleButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nombrevendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jToggleButton3)))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_nombrevendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addComponent(jToggleButton3)
                .addGap(26, 26, 26))
        );

        menu.addTab("Crear vendedor", jPanel3);

        jLabel11.setText("Vendedor");

        jLabel12.setText("Comprador");

        jLabel13.setText("Precio carro");

        jLabel14.setText("Vehiculo");

        jToggleButton4.setText("Guardar archivo");
        jToggleButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton4MouseClicked(evt);
            }
        });

        jToggleButton5.setText("Crear venta");
        jToggleButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(cb_comprador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(costotransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_vehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jToggleButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addComponent(jToggleButton4)
                .addGap(63, 63, 63))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cb_comprador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(costotransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_vehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton4)
                    .addComponent(jToggleButton5))
                .addGap(33, 33, 33))
        );

        menu.addTab("Crear venta", jPanel4);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Lab 7");
        arbolitosexy.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(arbolitosexy);

        jToggleButton6.setText("Seleccionar archivo");
        jToggleButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jToggleButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menu.addTab("Arbol ventas", jPanel5);

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Arbol clase");
        arbolclase.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane2.setViewportView(arbolclase);

        jToggleButton7.setText("Cargar al arbol");
        jToggleButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton7MouseClicked(evt);
            }
        });

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        limp.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane3.setViewportView(limp);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(395, 395, 395)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jToggleButton7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menu.addTab("Arbol Clases", jPanel6);

        area_salida.setColumns(20);
        area_salida.setRows(5);
        jScrollPane4.setViewportView(area_salida);

        jToggleButton8.setText("Escojer archivo");
        jToggleButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton8MouseClicked(evt);
            }
        });

        jToggleButton9.setText("Modificar");
        jToggleButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToggleButton9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(35, 35, 35))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jToggleButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jToggleButton9)))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        menu.addTab("Modificar", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked
        File archivo = null;
        FileWriter fw = null;
        BufferedWriter bw = null;
        try {
            archivo = new File("./Cliente.txt");
            String salida = "";
            fw = new FileWriter(archivo, true);
            bw = new BufferedWriter(fw);
            salida += "[\n\t";
            String nombre = txt_nombre.getText();
            salida += nombre + ",\n\t";
            int edad = Integer.parseInt(edad_spinner.getValue().toString());
            salida += edad + ",\n\t";
            String Profesion = txt_profesion.getText();
            salida += Profesion + ",\n\t";
            double sueldodisponible = Double.parseDouble(txt_sueldodisponible.getText());
            salida += sueldodisponible + "\n]\n";
            bw.write(salida);
            bw.flush();
            fw.close();
            bw.close();
            txt_sueldodisponible.setText("");
            txt_profesion.setText("");
            txt_nombre.setText("");
            Scanner leedor = new Scanner(archivo);
            String parasalida = "";
            while (leedor.hasNext()) {
                parasalida += leedor.next();

            }
            String aux = "";
            clientes = new ArrayList();

            String[] splitter = parasalida.split("]");

            for (int i = 0; i < splitter.length; i++) {
                String[] splitter2 = splitter[i].split(",");
                String marcax = splitter2[0];
                for (int j = 0; j < marcax.length(); j++) {
                    if (marcax.charAt(j) != '[') {
                        aux += marcax.charAt(j);
                    }

                }

                clientes.add(new Cliente(aux, Integer.parseInt(splitter2[1]), splitter2[2], Double.parseDouble(splitter2[3])));
                aux = "";
            }
            DefaultComboBoxModel modeloclientes = (DefaultComboBoxModel) cb_comprador.getModel();
            modeloclientes.removeAllElements();
            for (int i = 0; i < clientes.size(); i++) {
                modeloclientes.addElement(clientes.get(i));
            }
            cb_comprador.setModel(modeloclientes);

        } catch (Exception e) {
        }


    }//GEN-LAST:event_jToggleButton1MouseClicked

    private void jToggleButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton2MouseClicked
        File archivo = null;
        FileWriter fw = null;
        BufferedWriter bw = null;
        try {
            archivo = new File("./vehiculos.txt");
            String salida = "";
            fw = new FileWriter(archivo, true);
            bw = new BufferedWriter(fw);
            salida += "[\n\t";
            String marca = txt_marca.getText();
            salida += marca + ",\n\t";
            String color = txt_color.getText();
            salida += color + ",\n\t";
            String modelo = txt_modelo.getText();
            salida += modelo + ",\n\t";
            String año = txt_año.getText();
            salida += año + ",\n\t";
            double precioventa = Double.parseDouble(txt_precioventa.getText());
            salida += precioventa + "\n]\n";
            bw.write(salida);
            bw.flush();

            Scanner leedor = new Scanner(archivo);
            String parasalida = "";
            while (leedor.hasNext()) {
                parasalida += leedor.next();

            }
            String aux = "";
            vehiculos = new ArrayList();

            String[] splitter = parasalida.split("]");

            for (int i = 0; i < splitter.length; i++) {
                String[] splitter2 = splitter[i].split(",");
                String marcax = splitter2[0];
                for (int j = 0; j < marcax.length(); j++) {
                    if (marcax.charAt(j) != '[') {
                        aux += marcax.charAt(j);
                    }

                }

                vehiculos.add(new Vehiculo(aux, splitter2[1], splitter2[2], Integer.parseInt(splitter2[3]), Double.parseDouble(splitter2[4])));
                aux = "";
            }
            vehiculos.get(vehiculos.size() - 1).setId(modelo + marca);
            DefaultComboBoxModel modelovehiculo = (DefaultComboBoxModel) cb_vehiculo.getModel();
            modelovehiculo.removeAllElements();
            for (int i = 0; i < vehiculos.size(); i++) {
                modelovehiculo.addElement(vehiculos.get(i));
            }
            cb_vehiculo.setModel(modelovehiculo);

            fw.close();
            bw.close();

        } catch (Exception e) {
        }
        txt_marca.setText("");
        txt_año.setText("");
        txt_precioventa.setText("");
        txt_modelo.setText("");
        txt_color.setText("");
    }//GEN-LAST:event_jToggleButton2MouseClicked

    private void jToggleButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton3MouseClicked

        File archivo = null;
        FileWriter fw = null;
        BufferedWriter bw = null;
        try {
            archivo = new File("./Vendedor.txt");
            String salida = "";
            fw = new FileWriter(archivo, true);
            bw = new BufferedWriter(fw);
            salida += "[\n";
            String nombrevendedor = txt_nombrevendedor.getText();
            salida += nombrevendedor + "\t\n]";

            bw.write(salida);

            bw.flush();

            Scanner leedor = new Scanner(archivo);
            String parasalida = "";
            while (leedor.hasNext()) {
                parasalida += leedor.next();

            }
            String aux = "";
            vendedores = new ArrayList();

            String[] splitter = parasalida.split("]");

            for (int i = 0; i < splitter.length; i++) {
                String[] splitter2 = splitter[i].split(",");
                String marcax = splitter2[0];
                for (int j = 0; j < marcax.length(); j++) {
                    if (marcax.charAt(j) != '[') {
                        aux += marcax.charAt(j);
                    }

                }

                vendedores.add(new Vendedor(aux));
                aux = "";
            }
            DefaultComboBoxModel mo = (DefaultComboBoxModel) cb_vendedor.getModel();
            mo.removeAllElements();
            for (int i = 0; i < vendedores.size(); i++) {
                mo.addElement(vendedores.get(i));
            }
            cb_vendedor.setModel(mo);
            txt_nombrevendedor.setText("");
            bw.close();
            fw.close();

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jToggleButton3MouseClicked

    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked


    }//GEN-LAST:event_menuMouseClicked

    private void jToggleButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton5MouseClicked
        int venta = ventas.size() + 1;
        String codigo = "[\n";

        try {
            File archivo = new File("./ventadia");
            FileWriter fw = new FileWriter(archivo);
            BufferedWriter bw = new BufferedWriter(fw);

            Vendedor vdorhizolaoperacion = (Vendedor) cb_vendedor.getSelectedItem();
            Cliente clientecompro = (Cliente) cb_comprador.getSelectedItem();
            double costillo = Double.parseDouble(costotransaccion.getText());
            Vehiculo carroquesevendio = (Vehiculo) cb_vehiculo.getSelectedItem();
            codigo += "\t" + venta;
            codigo += "\n\t" + vdorhizolaoperacion.toString();
            codigo += "\n\t" + clientecompro.toString();
            codigo += "\n\t" + carroquesevendio.toString() + "\n]";
            ventas.add(new Venta(vdorhizolaoperacion, clientecompro, costillo, carroquesevendio));
            costotransaccion.setText("");
            bw.write(codigo);
            bw.flush();
            bw.close();
            fw.close();

        } catch (Exception e) {
        }


    }//GEN-LAST:event_jToggleButton5MouseClicked

    private void jToggleButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton4MouseClicked
        cb_comprador.removeAll();
        cb_vehiculo.removeAll();
        cb_vendedor.removeAll();
        String nombre = JOptionPane.showInputDialog("Digite el nombre del archivo");
        try {
            File archivo = new File("./" + nombre + ".txt");
            FileWriter fw = new FileWriter(archivo);
            BufferedWriter bw = new BufferedWriter(fw);
            for (int i = 0; i < ventas.size(); i++) {
                int venta = i + 1;
                String codigo = "[\n";
                Vendedor vdorhizolaoperacion = ventas.get(i).getVdorhizolaoperacion();
                Cliente clientecompro = (Cliente) ventas.get(i).clientecompro;
                double costillo = ventas.get(i).costotransaccion;
                Vehiculo carroquesevendio = ventas.get(i).carroquesevendio;
                codigo += "\t" + venta + ",";
                codigo += "\n\t" + vdorhizolaoperacion.toString() + ",";
                codigo += "\n\t" + clientecompro.toString() + ",";
                codigo += "\n\t" + carroquesevendio.getId() + "\n]\n";
                bw.write(codigo);
                codigo = "";

            }
            bw.flush();
            bw.close();
            fw.close();

        } catch (Exception e) {
        }


    }//GEN-LAST:event_jToggleButton4MouseClicked

    private void jToggleButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton6MouseClicked
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de texto", "txt");
        chooser.setFileFilter(filtro);
        int select = chooser.showOpenDialog(this);
        if (select == JFileChooser.APPROVE_OPTION) {
            File archivo2 = chooser.getSelectedFile();
            String codigox = "";
            try {
                Scanner leedor = new Scanner(archivo2);
                while (leedor.hasNext()) {
                    codigox += leedor.next();
                }

                arbolitosexy.setModel(limp.getModel());
                DefaultTreeModel modeloarbol = (DefaultTreeModel) arbolitosexy.getModel();

                DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloarbol.getRoot();
                String[] splitter = codigox.split("]");

                for (int i = 0; i < splitter.length; i++) {
                    String[] splitter2 = splitter[i].split(",");
                    DefaultMutableTreeNode idventa = new DefaultMutableTreeNode(quitarsigno(splitter2[0]));
                    DefaultMutableTreeNode nombrevendedor = new DefaultMutableTreeNode(splitter2[1]);
                    DefaultMutableTreeNode nombrecomprador = new DefaultMutableTreeNode(splitter2[2]);
                    DefaultMutableTreeNode idcarro = new DefaultMutableTreeNode(splitter2[3]);
                    idventa.add(nombrecomprador);
                    idventa.add(nombrevendedor);
                    idventa.add(idcarro);
                    raiz.add(idventa);

                }
                modeloarbol.reload();
                leedor.close();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jToggleButton6MouseClicked

    private void jToggleButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton7MouseClicked
        try {
            File clientes = new File("./Cliente.txt");
            Scanner leedorcliente = new Scanner(clientes);
            String clientesx = "";
            while (leedorcliente.hasNext()) {
                clientesx += leedorcliente.next();
            }
            arbolclase.setModel(limp.getModel());
            DefaultTreeModel modeloarbol = (DefaultTreeModel) arbolclase.getModel();

            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloarbol.getRoot();
            String[] splitter = clientesx.split("]");
            DefaultMutableTreeNode clientespapa = new DefaultMutableTreeNode("Clientes");
            for (int i = 0; i < splitter.length; i++) {
                String[] splitter2 = splitter[i].split(",");
                DefaultMutableTreeNode nombre = new DefaultMutableTreeNode(quitarsigno(splitter2[0]));
                DefaultMutableTreeNode edad = new DefaultMutableTreeNode(splitter2[1]);
                DefaultMutableTreeNode carrera = new DefaultMutableTreeNode(splitter2[2]);
                DefaultMutableTreeNode sueldo = new DefaultMutableTreeNode(splitter2[3]);
                clientespapa.add(nombre);
                clientespapa.add(edad);
                clientespapa.add(carrera);
                clientespapa.add(sueldo);
                raiz.add(clientespapa);

            }

            leedorcliente.close();
            File vendedores = new File("./Vendedor.txt");
            Scanner leedorvendedores = new Scanner(vendedores);
            String vendedorex = "";
            while (leedorvendedores.hasNext()) {
                vendedorex += leedorvendedores.next();
            }

            String[] splittervendedor = vendedorex.split("]");
            DefaultMutableTreeNode vendedorespa = new DefaultMutableTreeNode("vendedores");
            for (int i = 0; i < splittervendedor.length; i++) {
                String[] splitervendedoraux = splittervendedor[i].split(",");
                DefaultMutableTreeNode nombre = new DefaultMutableTreeNode(quitarsigno(splitervendedoraux[0]));
                vendedorespa.add(nombre);

                raiz.add(clientespapa);

            }

            leedorvendedores.close();
            File vehiculos = new File("./vehiculos.txt");
            Scanner leedorvehiculos = new Scanner(vehiculos);
            String vehiculox = "";
            while (leedorcliente.hasNext()) {
                vehiculox += leedorvehiculos.next();
            }

            String[] splittervehiculos = vendedorex.split("]");
            DefaultMutableTreeNode vehiculoss = new DefaultMutableTreeNode("vendedores");
            for (int i = 0; i < splittervehiculos.length; i++) {
                String[] splitervehiculosaux = splittervehiculos[i].split(",");
                DefaultMutableTreeNode nombre = new DefaultMutableTreeNode(quitarsigno(splitervehiculosaux[0]));
                clientespapa.add(nombre);

                raiz.add(clientespapa);

            }
            
            leedorvehiculos.close();
            File ventas = new File("./ventadia.txt");
            Scanner leedorventas = new Scanner(vehiculos);
            String ventasstr = "";
            while (leedorventas.hasNext()) {
               ventasstr += leedorventas.next();
            }

            String[] splitterventas = ventasstr.split("]");
            DefaultMutableTreeNode ventass = new DefaultMutableTreeNode("Ventas");
            for (int i = 0; i < splitterventas.length; i++) {
                String[] spliterventasaux = splitterventas[i].split(",");
                DefaultMutableTreeNode idventa = new DefaultMutableTreeNode(quitarsigno(spliterventasaux[0]));
                    DefaultMutableTreeNode nombrevendedor = new DefaultMutableTreeNode(spliterventasaux[1]);
                    DefaultMutableTreeNode nombrecomprador = new DefaultMutableTreeNode(spliterventasaux[2]);
                    DefaultMutableTreeNode idcarro = new DefaultMutableTreeNode(spliterventasaux[3]);
                    idventa.add(nombrecomprador);
                    idventa.add(nombrevendedor);
                    idventa.add(idcarro);
                    raiz.add(idventa);

            }
            
            leedorventas.close();
            modeloarbol.reload();

        } catch (Exception e) {
        }


    }//GEN-LAST:event_jToggleButton7MouseClicked

    private void jToggleButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton8MouseClicked
        JFileChooser chooser = new JFileChooser();
        archivomodificar=null;
        int selected =chooser.showOpenDialog(this);
        if (selected == JFileChooser.APPROVE_OPTION) {
             archivomodificar=chooser.getSelectedFile();
             
             try {
             Scanner leer= new Scanner(archivomodificar);
             while (leer.hasNext()) {                
                area_salida.append(leer.next());
            }   
             leer.close();
            } catch (Exception e) {
            }
             
        }
    }//GEN-LAST:event_jToggleButton8MouseClicked

    private void jToggleButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton9MouseClicked
        try {
            FileWriter fw = new FileWriter(archivomodificar);
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write(area_salida.getText());
            bw.flush();
            fw.close();
            bw.close();
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jToggleButton9MouseClicked
    public String quitarsigno(String id) {
        String arreglo = "";
        for (int i = 0; i < 10; i++) {
            if (id.charAt(i) != '[') {
                arreglo += id.charAt(i);
            }
        }
        return arreglo;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }
    File archivomodificar =null;
    ArrayList<Venta> ventas = new ArrayList();
    ArrayList<Vendedor> vendedores = new ArrayList();
    ArrayList<Vehiculo> vehiculos = new ArrayList();
    ArrayList<Cliente> clientes = new ArrayList();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree arbolclase;
    private javax.swing.JTree arbolitosexy;
    private javax.swing.JTextArea area_salida;
    private javax.swing.JComboBox<String> cb_comprador;
    private javax.swing.JComboBox<String> cb_vehiculo;
    private javax.swing.JComboBox<String> cb_vendedor;
    private javax.swing.JTextField costotransaccion;
    private javax.swing.JSpinner edad_spinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    private javax.swing.JTree limp;
    private javax.swing.JTabbedPane menu;
    private javax.swing.JTextField txt_año;
    private javax.swing.JTextField txt_color;
    private javax.swing.JTextField txt_marca;
    private javax.swing.JTextField txt_modelo;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_nombrevendedor;
    private javax.swing.JTextField txt_precioventa;
    private javax.swing.JTextField txt_profesion;
    private javax.swing.JTextField txt_sueldodisponible;
    // End of variables declaration//GEN-END:variables
}
